version: '3'

services:
    app:
        build: .
        depends_on:
            - postgres
        ports:
            - '$PORT:$PORT'
        volumes:
            - .:/app/
            - /app/node_modules
    postgres:
        image: postgres:13
        ports:
            - '5432:5432'
        volumes:
            - ./postgres:/var/lib/postgresql/data
        env_file:
            - .env
